theme: jekyll-theme-slate

title: Data Science and AI Portfolio \n Sam Walsh
description: This portfolio provides a brief description of the Data Science and Artificial Intelligence projects that I have completed. Each project title links to it's repository, which houses the code and more in depth information about the project. 
